name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '🔧 Other Changes'
    labels:
      - 'chore'
      - 'refactor'
      - 'style'
      - 'test'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No significant changes'

template: |
  ## What’s Changed

  $CHANGES

  **Full Changelog**: https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...$NEXT_TAG
