name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bugfix'
  - title: '📚 Documentation'
    labels:
      - 'docs'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'ci'
      - 'deps'
  - title: '🧪 Tests'
    labels:
      - 'test'

change-template: '- $TITLE (#$NUMBER)'
no-changes-template: '- No significant changes in this release.'

template: |
  ## 🔥 Release Highlights

  $CHANGES

  ---

  📦 **Version:** `$NEXT_TAG`  
  🕒 **Date:** ${{ date }}
  🔗 [Compare changes](https://github.com/${{ github.repository }}/compare/$PREVIOUS_TAG...$NEXT_TAG)
